# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "lambda-hello-world"

[default.build]
[default.build.parameters]
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_image_repos = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vh1h8exgoh4c"
s3_prefix = "lambda-hello-world"
region = "us-east-1"
image_repositories = ["HelloWorldFunction=774001425172.dkr.ecr.us-east-1.amazonaws.com/lambdahelloworldfaa5c4be/helloworldfunction19d43fc4repo"]

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
